# Delete the .github/ folder if you're not using GitHub
# To use, define an environment "Develop" and set the secrets PRICEFX_URL, PRICEFX_PARTITION, PRICEFX_USERNAME, PRICEFX_PASSWORD
name: Test & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - develop
      - qa
      - main
  pull_request:
    branches:
      - develop
      - qa
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Install with Maven
        run: mvn clean install
      - name: Test
        run: mvn test --batch-mode -pl pricefxSrc
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ./pricefxSrc/target/surefire-reports/TEST-*.xml
          retention-days: 14
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
  deploy-develop:
    name: Deploy to Pricefx Partition
    # Do not use pricefx-stream-maven-plugin in qa or production!
    #  Instead, use pfxpackage. See .gitlab-ci.yml
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: Develop
    needs: test # Only run if the test completed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Install with Maven
        run: mvn clean install
      - name: Deploy with Maven
        env:
          PRICEFX_URL: ${{ secrets.PRICEFX_URL }}
          PRICEFX_PARTITION: ${{ secrets.PRICEFX_PARTITION }}
          PRICEFX_USERNAME: ${{ secrets.PRICEFX_USERNAME }}
          PRICEFX_PASSWORD: ${{ secrets.PRICEFX_PASSWORD }}
        run: mvn --batch-mode --update-snapshots -pl pricefxSrc --settings .maven/settings.xml -P pricefx-partition net.pricefx.learn:pricefx-stream-maven-plugin:pricefx-deploy-all
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
